"""Demo Data Provider Adapter.

Reads and serves the authoritative demo outputs generated by demo/end_to_end_oil_spill_demo.py:
- demo/output/end_to_end_result.json
- demo/output/end_to_end_layers.geojson
Ensures demo data continues to work for testing, frontend visualization, and offline development.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List, Optional
from backend.core.config import settings
from backend.core.logging import logger


class DemoDataProvider:
    """Provides validated access to pre-computed demonstration artifacts."""

    def __init__(self, demo_dir: Optional[Path] = None):
        self.demo_dir = demo_dir or settings.DEMO_OUTPUT_DIR
        self.result_json_path = self.demo_dir / "end_to_end_result.json"
        self.layers_geojson_path = self.demo_dir / "end_to_end_layers.geojson"

    def load_latest_result(self) -> Dict[str, Any]:
        """Load the authoritative demo end_to_end_result.json."""
        if self.result_json_path.exists():
            try:
                with open(self.result_json_path, "r", encoding="utf-8") as f:
                    data = json.load(f)
                    # Annotate provenance explicitly
                    if "provenance" not in data:
                        data["provenance"] = {
                            "data_source_mode": "DEMO",
                            "sensor": data.get("spill_metadata", {}).get("sensor", "Sentinel-1 SAR C-Band (IW)"),
                            "satellite_provider": "ESA Copernicus Sentinel-1 (Demo Profile)",
                            "ocean_provider": "Copernicus Marine / ECMWF ERA5 (Arabian Sea Domain)",
                            "ais_provider": "NOAA Historical Format (Synthetic Traffic Corridor)",
                            "pipeline_version": "1.0.0",
                            "executed_at": data.get("pipeline_execution", {}).get("execution_timestamp"),
                        }
                    return data
            except Exception as exc:
                logger.error(f"Error parsing demo result JSON: {exc}")

        return {
            "status": "NO_DATA",
            "message": f"Demo result not found at {self.result_json_path}. Run demo/end_to_end_oil_spill_demo.py to generate.",
        }

    def load_latest_layers_geojson(self) -> Dict[str, Any]:
        """Load the authoritative demo GeoJSON FeatureCollection."""
        if self.layers_geojson_path.exists():
            try:
                with open(self.layers_geojson_path, "r", encoding="utf-8") as f:
                    return json.load(f)
            except Exception as exc:
                logger.error(f"Error parsing demo GeoJSON: {exc}")

        return {
            "type": "FeatureCollection",
            "features": [],
        }

    def get_demo_investigations(self) -> List[Dict[str, Any]]:
        """Return standardized investigations list derived from demo data."""
        res = self.load_latest_result()
        spill = res.get("spill_metadata", {})
        gis = res.get("gis_measurement", {})
        suspect = res.get("primary_suspect", {})
        centroid = gis.get("centroid", {"latitude": 18.523598, "longitude": 72.481513})

        inv1 = {
            "id": spill.get("spill_id", "SAR-20250101-IND-0042"),
            "title": "Offshore Mumbai Shipping Corridor Incident",
            "status": "Active",
            "priority": "High",
            "region": "Arabian Sea (Sector IND-West)",
            "coordinates": {
                "latitude": centroid.get("latitude", 18.523598),
                "longitude": centroid.get("longitude", 72.481513),
            },
            "spill_area_km2": gis.get("area", {}).get("sq_kilometers", 3.9275),
            "detection_time": spill.get("detection_timestamp", "2025-01-01T05:00:00+00:00"),
            "suspect_vessel": f"{suspect.get('vessel_name', 'PACIFIC VOYAGER')} (MMSI: {suspect.get('mmsi', 413999001)})",
            "match_confidence": round((suspect.get("scores", {}).get("overall", 0.954) or 0.954) * 100, 1),
            "evidence_nodes_count": 8,
            "sar_epoch": "05:00Z",
            "created_at": "2025-01-01T05:30:00Z",
        }

        inv2 = {
            "id": "SAR-20250102-GOM-0019",
            "title": "Gulf of Mexico Mississippi Canyon Sector 4A",
            "status": "Completed",
            "priority": "Medium",
            "region": "Gulf of Mexico",
            "coordinates": {"latitude": 27.382, "longitude": -90.0841},
            "spill_area_km2": 6.84,
            "detection_time": "2025-01-02T11:24:00 UTC",
            "suspect_vessel": "BALTIC TRADER",
            "match_confidence": 78.2,
            "evidence_nodes_count": 5,
            "sar_epoch": "11:24Z",
            "created_at": "2025-01-02T12:00:00Z",
        }
        return [inv1, inv2]

    def get_demo_reports(self) -> List[Dict[str, Any]]:
        """Return standardized forensic dossier reports derived from demo data."""
        res = self.load_latest_result()
        spill = res.get("spill_metadata", {})
        suspect = res.get("primary_suspect", {})
        score = round((suspect.get("scores", {}).get("overall", 0.9536) or 0.9536) * 100, 2)

        return [
            {
                "id": "REP-2025-0042",
                "investigation_id": spill.get("spill_id", "SAR-20250101-IND-0042"),
                "title": f"MARPOL Annex I Hydrocarbon Discharge Forensic Dossier: {suspect.get('vessel_name', 'PACIFIC VOYAGER')}",
                "generated_at": "2025-01-01T08:30:00 UTC",
                "author": "Indian Coast Guard / Maritime Forensic Taskforce",
                "status": "Final",
                "target_vessel": suspect.get("vessel_name", "PACIFIC VOYAGER"),
                "imo": suspect.get("imo", "IMO9384813"),
                "mmsi": suspect.get("mmsi", 413999001),
                "attribution_score": score,
                "summary": (
                    "Integrated forensic attribution established through backward Lagrangian drift hindcasting (4h), "
                    "Sentinel-1 C-Band morphology (3.927 km²), and coincident AIS Class-A trajectory match "
                    "(0.572 km minimum distance at 01:00 UTC)."
                ),
                "marpol_violation_risk": "High",
                "sha256_hash": "a4c28f11d9487c65c2718ecbf928821a4de8b39c0fa1107d6bc388ea210cfbc4",
                "jurisdiction": "UNCLOS / MARPOL 73/78 Annex I / DG Shipping India",
            }
        ]


demo_provider = DemoDataProvider()
