"""Origin Candidate ORM Model."""

from __future__ import annotations

from sqlalchemy import Column, DateTime, Float, ForeignKey, Index, Integer, JSON, String
from sqlalchemy.orm import relationship
from backend.core.database import Base
from backend.models.base import TimestampMixin


class OriginCandidateModel(Base, TimestampMixin):
    """Candidate release origin generated by reverse Lagrangian clustering."""

    __tablename__ = "origin_candidates"

    id = Column(Integer, primary_key=True, autoincrement=True)
    investigation_id = Column(String(64), ForeignKey("investigations.investigation_id", ondelete="CASCADE"), nullable=False, index=True)
    latitude = Column(Float, nullable=False)
    longitude = Column(Float, nullable=False)
    origin_timestamp = Column(DateTime(timezone=True), nullable=False)
    score = Column(Float, nullable=False)
    uncertainty_radius_km = Column(Float, nullable=False)
    rank = Column(Integer, default=1, nullable=False)
    metadata_json = Column(JSON, default=dict)

    investigation = relationship("InvestigationModel", back_populates="origin_candidates")

    __table_args__ = (
        Index("idx_origin_investigation_rank", "investigation_id", "rank"),
    )
